const router = require('express').Router();
const registrarActividadMiddleware = require('../middleware/auditoria');
const authRoutes = require('./auth.routes');
const recuperacionRoutes = require('./recuperacion.routes');
const consejosRoutes = require('./consejos.routes');
const familiasRoutes = require('./familias.routes');
const miembrosRoutes = require('./miembros.routes');
const formulariosRoutes = require('./formularios.routes');
const reportesRoutes = require('./reportes.routes');
const configuracionRoutes = require('./configuracion.routes');
const catalogoRoutes = require('./catalogo.routes');
const preguntaSeguridadRoutes = require('./preguntaSeguridad.routes');
const auditoriaRoutes = require('./auditoria.routes');
const backupRoutes = require('./backup.routes');

router.use(registrarActividadMiddleware);
router.use('/auth/recuperacion', recuperacionRoutes);
router.use('/auth', authRoutes);
router.use('/consejos', consejosRoutes);
router.use('/familias', familiasRoutes);
router.use('/miembros', miembrosRoutes);
router.use('/formularios', formulariosRoutes);
router.use('/reportes', reportesRoutes);
router.use('/configuracion', configuracionRoutes);
router.use('/catalogos', catalogoRoutes);
router.use('/preguntas-seguridad', preguntaSeguridadRoutes);
router.use('/auditoria', auditoriaRoutes);
router.use('/backup', backupRoutes);

module.exports = router;
